### ISSUE TITLE
Trouble reading a jdx file

### ISSUE THREAD

**Issue by ocefpaf** [nzhagen/jcamp#13]
Thanks for this software! It worked really nice with a set of files I had here. However, the lab just sent me a new set and nothing is working.

These are the files that are failing: https://www.dropbox.com/sh/wsxyeod21gq37dw/AAA4x6_tWsGd9KghGWMTJ-wPa?dl=0

Full disclaimer: I have little idea what jcamp data is and what the software is doing!
I am only a computer guy trying to help a friend create some nice pictures from the results :smile:

**Comment by nzhagen** [comment]
Felipe,

Thanks for the tip. That's some weird-looking data format you have there. I
wrote the original version of JCAMP based on the paper giving the file
specifications for the format. Since then a few companies have added a
couple of formats of their own, and JCAMP has adapted to those as well. Is
there a specification document for this format you show? I've tried looking
online and haven't found anything connecting "Varian" with a new kind of
JDX format.

- Nathan

**Comment by ocefpaf** [comment]
>  Is there a specification document for this format you show?

I'll ask people at the lab if there is anything but I'm not sure they know.

> I've tried looking online and haven't found anything connecting "Varian" with a new kind of JDX format.

Thanks for looking! However, I'm not sure how much effort it is worth on pursuing this. The people I'm trying to help use origin and matlab solutions to read those files. My goal was to bring them to the OSS world but they are fine with their current tools.

Thanks again!

**Comment by bryanhanson** [comment]
I’m a lurker here — my interest is that I have a package in the R language called readJDX that, well, reads jcamp files!  So I like to keep my eye on the python world too.

Using readJDX I can read several of Filipe’s files, but I cannot read two of them.  I know why after studying this for a bit: these two files use a particular combination of SQZ, DIF and DUP formats that doesn’t come up too often (I have tested hundreds of files and not run into it).  I have a fix in mind but no time for a few days at least.  I don’t think it has anything in particular to do with Varian (RIP), other than the code they wrote acting on these particular data sets produces this combination of “features”.

Sounds like your people have a fix so they can move forward.  Let me just say thanks for sharing the files, this issue will improve my code!

Bryan

**Comment by ocefpaf** [comment]
Thanks for the info @bryanhanson! I'll pass that along to the people in the lab (ping @juoceano).

> This doesn't surprise me, the JCAMP standard allows a lot of flexibility and I have seen several errors in JCAMP writers from respected instrument manufacturers.

That is not very encouraging :-(

**Comment by smnrock** [comment]
> (the line is in DIF mode here, where a digit is not allowed)

I could be wrong, but I think digit is allowed next to DUP character, here it is W.  I assume, this means, the previous Y value or (Y + or - dif) is repeated W8 times. ie., 58 times.

**Comment by bryanhanson** [comment]
@smnrock You are correct and I was wrong.  I am updating `readJDX` and have fixed this problem. I can now read all the files posted by Filipe.  Thanks for your comment.

**Comment by vorobus** [comment]
Hi, @nzhagen , thank you for very nice code!
Unfortunately, I can't read the file generated from the online platform PredictNMR.
 

```
 ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-37-b95fdf34129f> in <module>()
----> 1 j.JCAMP_reader(filename='dataset/predictedSpectrum.jdx')

C:\Users\vvv\Anaconda2\envs\quantum\lib\site-packages\jcamp.pyc in JCAMP_reader(filename)
     38 def JCAMP_reader(filename):
     39     with open(filename, 'r') as filehandle:
---> 40         data = jcamp_read(filehandle)
     41     data['filename'] = filename
     42     return data

C:\Users\vvv\Anaconda2\envs\quantum\lib\site-packages\jcamp.pyc in jcamp_read(filehandle)
    107             ## The pair of lines below involve regex splitting on floating point numbers and integers. We can't just
    108             ## split on spaces because JCAMP allows minus signs to replace spaces in the case of negative numbers.
--> 109             datavals = jcamp_parse(line)
    110             xstart.append(float(datavals[0]))
    111             xnum.append(len(datavals) - 1)

C:\Users\vvv\Anaconda2\envs\quantum\lib\site-packages\jcamp.pyc in jcamp_parse(line)
    335             prev_c = line[i-1]
    336             mul = DUP_digits[c]
--> 337             newline.pop(i + offset)
    338             for j in range(mul - 1):
    339                 newline.insert(i + offset, prev_c)

IndexError: pop index out of range
```


Can you give me the idea, why it's not working? 

https://www.nmrdb.org/new_predictor/index.shtml?v=v2.116.1

**Here is the file:**

> ##YUNITS=	Intensity
> ##NPOINTS=	32768
> ##FIRSTX=	0
> ##LASTX=	11
> ##FIRSTY=	0
> ##LASTY=	0
> ##XFACTOR= 0.0003357036042359691
> ##YFACTOR= 2000
> ##MAXY= 1653988535.084186
> ##MINY= 0
> ##DELTAX= 0.0003357036042359691
> ##XYDATA=(X++(Y..Y))
> 0@%S0150J%S4J%ZJ%WJ%UJ%UJ%UJ%TJ%TJ%TJ%J%J%TJ%J%J%J%J%J%J%JT%J%J%JT%J%J%J%J%JT%J%TJ%J%J%J%TJ%TJ%J%TJ
> 10264D0%J%J%JXKVLUNMOTPQRJ0J2J4J5J7K0K2K5K7L2L5M0M4N0N5O2O9P7Q6R5J05J17J30J43J59J75J93K12K33K57K82
> 10320B923L09L38L71M04M42M82N24N71O21O74P30P92Q57R26J000J079J162J251J345J444J550J660J777J901K029K166
> 10346B9328K307K457K612K774K944L119L303L493L689L892M102M319M541M771N005N246N492N742N999O258O522O789
> 10368A24704P060P332P607P882Q159Q436Q711Q986R258R528R794J0056J0313J0565J0809J1046J1276J1496J1706
> 10387C04724J1907J2096J2273J2439J2590J2728J2851J2960J3053J3130J3190J3234J3260J3269J3260J3233J3188
> 10404E23385J3123J3041J2940J2821J2683J2527J2352J2159J1949J1721J1476J1213J0935J0639J0329J0003R662R307
> 10422G32265Q938Q556Q161P754P336O907O468O018N561N094M620M140L651L159K661K158J652J144O32J19l94r07j420
> 10445H24273j932k441k948l450l949m443m930n410n885o349o807p253p689q115q528q929r316r691j0050j0394j0722
> 10466F85042j1034j1330j1607j1867j2109j2331j2537j2721j2887j3033j3159j3265j3353j3419j3467j3494j3503
> 10483D69926j3492j3463j3416j3350j3268j3167j3052j2919j2773j2611j2436j2248j2048j1836j1614j1381j1141
> 10500B55711j0891j0635j0372j0104r830r553r272q990q705q419q135p849p565p283p004o727o454o185n920n660n405
> 10521H4753n157m913m676m445m222m004l794l590l395l205l023k848k680k520k366k220k079j946j820j698j585j477
> 10543A7090j374j278j186j101j020r44q73q06p44o85o31n80n33m89m48m10l75l43l12k85k60k35k15j94j76j60j44j30
> 10571A159j18j06r5q5p7o9o2n5n0m4l9l5l1k7k5k1j9j7j5j3j2j0qTponmTlTkljkjkjT%jT%j%j%j%j%j%jT%j%jT%jU%jW
> 10641E3%jT1%jZ%jV%jT%jT%jT%jT%j%j%j%Tj%j%Tj%Tj%Tj%Uj%Wj%Xj%S3j%W42J%XJ%UJ%J%JXKJKTLUMUONPTRTJ1TJ4T
> 11323A31J7J8K1K2K6K8L1L5L8M3M6N2N8O3O9P7Q4R2J01J11J22J32J46J58J73J88K05K22K42K62K85L08L33L60L89M19
> 11359E107M52M87N24N62O04O47O94P42P94Q48R05R64J028J093J163J234J309J388J470J555J643J735J829J928K030
> 11384C2735K135K242K354K469K586K706K829K955L084L214L347L483L619L758L897M039M180M323M465M609M750M893
> 11406A08672N033N172N310N445N579N708N835N958O077O191O300O404O502O594O679O758O827O891O945O992P028P056
> 11428B45956P075P083P081P069P046P012O967O912O844O766O675O573O461O335O200O052N893N723N543N351N150M938
> 11450C86705M716M486M246L997L740L477L204K927K642K352K057J759J455J149Q40N30K18r4m06p18j028j335j641
> 11473D25278j942k240k533k821l103l378l647l909m162m407m642m870n086n294n490n675n851o014o166o307o436o552
> 11495C24753o658o751o831o901o958p003p037p058p069Tp056p033p001o956o903o840o767o685o594o496o389o275
> 11517A74423o153o024n890n749n602n450n293n132m967m798m625m449m271m090l907l723l537l350l162k973k784k595
> 11539G5899k407k218k030j842j656j471j287j104r22p43n66l89k16m3J26K95M59O22P83R42J096J250J400J548J694
> 11564F9220J835J975K112K245K377K504K630K751K871K986L099L208L315L417L518L613L706L796L881L963M042M117
> 11586A37181M188M254M318M378M432M484M531M573M612M647M676M701M722M738M750M757M759M756M749M736M719M696
> 11608B38357M669M637M599M557M510M456M399M337M268M196M117M035L948L855L757L656L548L438L322L203L078K950
> 11630C25892K819K682K543K401K254K106J953J798J642J482J320J157R92Q25O58M89L21J50j9j89l58n28o96q63j028
> 11655C49803j194j356j518j676j832j987k138k286k431k572k711k846k976l104l226l344l459l569l673l775l870l961
> 11677B90299m048m128m205m277m343m404m461m512m558m600m636m668m694m717m733m746m753m757m756m750m741m726
> 11699A90086m709m686m661m632m598m563m522m479m433m385m332m278m221m162m100m036l970l903l834l763l690l617
> 11721I6512l543l466l390l313l234l156l077k998k919k839k759k681k602k523k445k368k291k216k140k065j993j920
> 11743C6574j849j780j711j643j578j513j450j388j328j270j212j157j103j051j000r51r04q58q13p71p30o90o53o16
> 11767H555n81n47n16m85m56m28m01l77l52l29l08k88k67k50k32k16k00j86j72j59j47j35j25j14j05r6q8p9p2o5n9n2
> 11799F68m6m0l4k9k4j9j4j0mJNJ1J6K1K6L2L9M4N2N8O6P5Q3R2J02J13J25J37J50J65J79J97K13K33K53K74K97L22L48
> 11838D177L76M05M38M70N06N44N84O26O70P17P66Q18Q73R29R90J053J118J186J258J332J410J489J573J659J749J840
> 11864B9556J936K033K135K238K343K453K564K678K793K911L031L153L276L401L526L653L781L908M037M165M293M420
> 11886I8284M547M672M796M918N037N156N270N381N490N594N694N790N880N967O047O122O190O252O308O356O397O431
> 11908B22579O457O475O485O486O479O462O438O403O361O308O246O175O095O004N906N797N679N553N416N272N118M956
> 11930C55150M786M607M421M227M026L818L602L382L155K923K684K443K195J945J691J434J175R13O50L85J21j43m09
> 11953D09181o72r34j195j453j709j961k210k455k695k930l160l384l603l815m020m218m409m592m768m935n094n244
> 11975C39725n387n520n643n760n865n962o050o129o198o258o310o351o385o409o425o432o431o421o404o379o345o306
> 11997B04355o259o205o145o078o006n927n844n756n662n565n463n358n249n138n023m906m787m666m544m420m295m170
> 12019H6889m045l918l794l668l543l420l297l176l056k938k821k706k595k484k376k271k167k068j970j875j784j694
> 12041B5223j608j524j444j366j292j219j151j084j021r61r03q47p94p45o97o51o08n68n30m92m59m26l96l67l40l15
> 12067C415k91k68k49k28k11j94j78j63j50j38j26j15j05r6q7q0p2o6o0n4m9m5m0l6l3l0k6k4k2j9j7j6j4j2j1j0rqpoT
> 12108D4nmTlUkVjkjU%jT%j%Tj%Uj%Wj%S0j%T1j%S280J%XJ%TJ%TJ%JXKWLMLMNTOPQTJ0TJ2J3J5J7J8K1K2K6K8L1L5L8M2
> 13505D11M6N2N6O2O9P5Q2R0R8J08J18J28J40J52J66J80J95K11K30K47K68K89L11L36L60L88M17M46M78N12N48N84O23
> 13538H476O64P07P52P98Q47Q98R51J005J063J121J182J245J309J377J445J515J587J662J736J814J892J972K052K135
> 13562D0205K217K302K385K471K557K641K728K813K899K984L068L151L235L315L396L475L551L626L700L771L839L905
> 13584A08234L969M029M087M142M193M242M286M328M366M400M430M458M480M499M515M526M533M537M536M532M524M512
> 13606B04358M495M476M452M424M394M358M320M278M232M183M130M075M014L953L886L817L745L670L591L510L425L338
> 13628B93124L248L155L060K961K860K756K651K542K430K318K202K085J964J843J719J594J466J337J207J075R42Q07
> 13650C39346O72N36L98K61J22j7j56k95m34n73p11q50r87j124j260j395j529j660j792j921k048k175k298k419k539
> 13675C15152k656k770k883k992l099l202l303l401l496l586l675l760l840l919l992m063m129m192m250m306m356m403
> 13697B34879m446m485m519m550m575m597m615m628m637m641m642m637m630m617m601m580m556m526m494m458m417m373
> 13719A34655m325m275m220m163m102m038l973l903l832l758l682l605l525l444l361l278l193l107l020k934k846k759
> 13741E5312k671k584k497k410k325k239k155k072j991j909j830j752j676j602j528j457j388j321j256j192j130j072
> 13763A5255j014r59r05q55q05p59p13o70o29n90n52n17m83m51m21l91l65l39l15k92k71k51k31k14j98j82j68j54j42
> 13792A419j30j19j10j00r1q4p6o9o4n7n2m7m3l9l5l2k9k6k3k1j9j7j5j3j2j1j0rpToTnmTlUkUjkjV%jT%Tj%Tj%Xj%S4590
> 28445@J%XJ%TJ%J%JXKJKLKLMUNOTPQJ0TJ2J3J5J6J9K0K3K6K9L3L5M0M5M9N5O0O7P4Q2R0R9J10J20J32J45J58J74J90
> 28509B018K07K26K47K68K92L17L44L73M04M36M72N08N49N90O35O81P32P84Q40Q97R59J023J090J160J234J310J390
> 28536A9986J473J559J648J740J835J933K034K137K244K353K464K577K692K809K928L048L169L290L413L535L658L779
> 28558G6304L901M021M139M255M370M482M591M695M798M895M988N076N159N236N308N373N432N484N528N567N597N620
> 28580A84819N635N642N641N633N616N591N559N518N470N414N352N280N204N119N028M932M829M722M608M490M368M242
> 28602B98712M112L979L843L705L565L423L280L136K991K846K701K557K412K268K125J984J843J704J565J429J293J159
> 28624C56632J027Q94P64O35N06L78K51J25kj29k55l81n09o36p64q94j023j155j287j420j555j691j828j966k106k246
> 28650C41365k387k528k672k813k957l099l241l382l523l660l798l932m064m192m319m440m558m671m779m882m979n071
> 28672B57418n157n234n307n372n430n479n523n557n584n604n615n618n614n602n582n555n519n478n428n373n310n241
> 28694A37236n167n087n001m910m815m716m612m506m395m283m168m051l932l812l691l569l448l326l205l084k964k846
> 28716D7648k729k613k500k388k279k172k068j967j868j772j679j589j502j419j338j260j187j114j047r82r19q60q05
> 28739I591p50p00o52o06n64n23m85m50m16l84l55l27l01k77k55k34k14j97j80j64j50j37j25j13j03r4q5p7p0o3n7n1
> 28771D32m6m2l7l4l0k7k5k1k0j7j5j4j2j1j0qTponTmlVkTjkjV%jT%j%Uj%Xj%U946
> 32767@
> ##END=

**Comment by nzhagen** [comment]
Vadim,
    I apologize for the slow response. You emailed just as the semester at my university was ending, and so I had to prioritize my classes before I could spend time on this. As for the file parsing error - I can see that it fails right on the first line of the data. I'm not very familiar with the JCAMP's encoding rules, but I tried replacing the "DUP" characters in that line manually, and I found that it would run without error. This means that the parsing code is wrong, and not the file. Looking more carefully, I could see that the code for this was written poorly. I rewrote it to be much simpler, and now it runs without error. Please give it a try!

**Comment by nzhagen** [comment]
I can see that this same error is occurring in the much simpler code inside one of the tests inside "tests.py". So that is an easier place to start debugging the problem with parsing the DUP characters.

**Comment by nzhagen** [comment]
I found an error in my interpretation of the DUP character codes. With that fixed, the tests now run without errors, and the file included above by Vorobus also runs without error. So I believe that I can finally close off this issue.
