### ISSUE TITLE
Reading multi-block JCAMP

### ISSUE THREAD

**Issue by raphaelproux** [nzhagen/jcamp#17]
Hi,

We generate JDX files with multi-block structure with our spectrometer. I understand there is no way to handle this directly in the library at this stage?
What I did crudely is
```
with open(r'spectra_multi_block.JDX') as fp:
    jcamp_list = fp.read().split(r'##END=')
jcamp_list = [jcamp_str.splitlines() for jcamp_str in jcamp_list]
jcamp_spectra = []
for jcamp_text in jcamp_list:
    jcamp_spectra.append(jcamp.jcamp_read(jcamp_text))
```

Like this, `jcamp_spectra` contains a list of blocks, with still some empty ones at the end due to the crude method of splitting, but this is easy to refine. You can have a look in section 11 of the [JCAMP original specification](http://old.iupac.org/jcamp/protocols/dxir01.pdf).

What do you think of this? Do you want to integrate it? I can make a pull request if you'd like.

Thanks,
Raphael

EDIT: I looked at your code and it seems it should handle it properly... Not sure what is the problem. In my case, if I try to parse the file it just returns some kind of concatenated version with all the XY data blocks together. I will get back with more info or an example...

**Comment by raphaelproux** [comment]
Ok, so I found out that our spectrometer does not exactly respect the standard, it uses `##DATATYPE=` instead of `##DATA TYPE=`. When changing the dataset label to the correct version, it works very well.
Can I suggest changing the test that detects the datatype flag to handle both cases?

**Comment by raphaelproux** [comment]
I created a pull request for this issue: #19

**Comment by nzhagen** [comment]
Sure. Sounds like a good idea, and I've merged your patch into the main branch. Thanks!

**Comment by nzhagen** [comment]
Re-reading your comment on the issue, it looks like the code fails to parse your file correctly. If you find a fix, I can patch it in. Or if you would like to send the file, I can use it to start a testing suite and make sure that the code parses it correctly. I've never encountered one of those multi-block files....

**Comment by raphaelproux** [comment]
Hi @nzhagen 
Thanks for the feedback. Indeed the original multi-block (or compound) code that was integrated by pull request #16 was working well but failed because of the `DATA LINK` tag being written as `DATALINK`. Including this in the code solved the problem.
