### ISSUE TITLE
Multi-line comment and data processing sections

### ISSUE THREAD

**Issue by raphaelproux** [nzhagen/jcamp#18]
Hi again :)

I open a separate issue for this. In the files generated by our spectrometer, the `##DATA PROCESSING=` and `##COMMENTS=` sections of the files are generally multiline. This is not super clear in the original specification, they only talk of having multiline data for the data arrays (like `##XYDATA=`). Anyway, I think it would be useful if the parser could handle a multiline data-set (as per the definition of the JCAMP spec). 

Is this possible?

Thanks,
Raphael

**Comment by raphaelproux** [comment]
There is a pull request about this: #20

**Comment by nzhagen** [comment]
Yes, definitely. This also sounds like a good idea -- I'll merge it in. Do you have an example file I could add to the repo for testing purposes? As the code gets more complex, I'd eventually like to build a testing suite like I've done for some of my other projects.

**Comment by raphaelproux** [comment]
Great, thanks! I made another pull request to include a test file with a comments section that spans on multiple lines and a small test code added at the end of jcamp.py. Feel free to modify it as you see fit.

**Comment by nzhagen** [comment]
I went ahead and put in your patch. I'm hoping to make a testing suite, but right now I don't have enough time to devote to it, so I hope to get back to it before long.

**Comment by raphaelproux** [comment]
Of course, I can understand that! However, you did a great job, the package is simple and neat :)
