### ISSUE TITLE
Latest version is not installed with pip install jcamp

### ISSUE THREAD

**Issue by RussBowers** [nzhagen/jcamp#22]
The command "pip install jcamp", when entered into the Anaconda powershell, installs an old version of jcamp.py with problems decoding white space. My workaround was to manually replace the older jcamp.py in \conda\Lib\site-packages. This was a big waste of my time tracking down this problem. 

Nathan, can you please fix this? 

Thanks, Russ

**Comment by nzhagen** [comment]
Just uploaded the current v1.2.2 to PyPi.

Sorry for the long wait!
